project:
  type: website
  output-dir: docs

website:
  title: "Rahul Reghu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - tab1.qmd
      - Favourites.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



